### ISSUE TITLE
Same thing for ECS?

### ISSUE THREAD

**Issue by JohnPreston** [awslabs/aws-orbit-workbench#358]
Hi,
Any plans on implementing the same solution to deploy with ECS too ? EKS / K8s might be popular, but ECS is your very own docker containers orchestrator, why is it not treated with at least as much priority as EKS ?
I read Jupyter plugin, so sure there might already be something there for K8s, but what about AWS providing an ECS plugin?
Thanks,

**Comment by abaror** [comment]
Hi John,

What Orbit provides is much more than a Jupyter Plugin.   Orbit is an entire secured multi-team environment for data analytics.  We create secured team spaces that enable team collaboration and in the same time data isolation and security for that team.  The Jupyter Plugin is only a small part of the UI for this infrastructure.  ECS has quite a different infrastructure and tooling than EKS and we chose to start with EKS because of its popularity and wealth of tooling.   At some point, we can also provide an ECS deployment, but it will depend on the community priority and the resources available to us.

**Comment by abaror** [comment]
At this point we have gone too far into K8 land with integration with Istio and Kubeflow.  This project will never be running on ECS.
