### ISSUE TITLE
EMR on EKS is broken.

### ISSUE THREAD

**Issue by abaror** [awslabs/aws-orbit-workbench#670]

**Comment by abaror** [comment]
when we moved to Kubeflow with user spaces , the EKS stopped working.   https://docs.aws.amazon.com/emr/latest/EMR-on-EKS-DevelopmentGuide/setting-up-cluster-access.html

**Comment by stthoom** [comment]
1) Identified EFS file path change passed to applicatonConfiguration as below instead of "/efs/share"

"spark.kubernetes.driver.volumes.persistentVolumeClaim.team.mount.path":"/efs/shared",

2) After recreating the virtual cluster manually using boto3, the EMR on EKS notebook executes well. Debugging the plugin based virtual cluster deployment issues. Per plugin code, the  parameters seems right. 

Debug log for job says-
-  'failureReason': 'CLUSTER_UNAVAILABLE',
-  'stateDetails': 'Cluster orbit-dev-env does not exist.'

**Comment by stthoom** [comment]
https://github.com/awslabs/aws-orbit-workbench/pull/715

**Comment by stthoom** [comment]
Pending testing in dev account based regression pipeline.
