### ISSUE TITLE
fix NB_PREFIX url

### ISSUE THREAD

**Issue by chamcca** [awslabs/aws-orbit-workbench#749]

**Comment by dgraeber** [comment]
For reference: the link to the notebooks from KF is not clearly editable.  For example, in the KF Servers homepage, the link 'Connect' does not reflect the location of the VSCode location directly.  The NB Code in pod.py (in orbit-controller) works correctly.  Since we removed kubespawner and replaced it with KF, the parameter 'default_url' is not able to be injected.

**Comment by dgraeber** [comment]
The NB code appears to work correctly.  More research into KF and the link it provides is needed
